---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:               # Интерфейс смотрит в сеть с inetRouter
      addresses:
      - 192.168.0.2/28    # Имеет такой адрес
      routes:
      - to: 0.0.0.0/0     # И ходит куда угодно 
        via: 192.168.0.1  # через centralRouter
    eth2:
      addresses:
      - 192.168.56.13/24  # Интерфейс Vagrant