---
network:
  version: 2
  renderer: networkd
  ethernets:

    enp0s8:                 # Интерфейс смотрит в Интернет
      addresses:
      - 192.168.255.2/30    # Имеет такой адрес
      routes:
      - to: 0.0.0.0/0       # И ходит в интернет 
        via: 192.168.255.1  # через 192.168.255.1 (inetRouter1)

    enp0s9:                 # Интерфейс смотрит в сеть с inetRouter2
      addresses:
      - 192.168.255.6/30    # Имеет такой адрес

    enp0s10:                # Интерфейс cмотрит в сеть 192.168.0.0/28, где есть centralServer
      addresses:
      - 192.168.0.1/28      # Имеет такой адрес
    
    enp0s19:                # Интерфейс Vagrant
      addresses:
      - 192.168.56.12/24