---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.255.1/30 
      routes:
      - to: 192.168.0.0/24  # Ходит в локальные сети 192.168.0.0/24 через CentralRouter (192.168.255.2)
        via: 192.168.255.2
      - to: 192.168.255.0   
        via: 192.168.255.2
    enp0s19:                
      addresses:
      - 192.168.56.10/24
